use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Tool call result status.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub enum ToolCallResultStatus {
    Success,
    Error,
    Cancelled,
}

/// Tool call result.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ToolCallResult {
    pub call: stakai::ToolCall,
    pub result: String,
    pub status: ToolCallResultStatus,
}

/// Streaming progress info for a tool call being generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCallStreamInfo {
    /// Tool name, which may be empty if it has not streamed yet.
    pub name: String,
    /// Estimated token count of arguments streamed so far.
    pub args_tokens: usize,
    /// Optional description extracted from arguments.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Tool call result progress update.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCallResultProgress {
    pub id: Uuid,
    pub message: String,
    /// Type of progress update for specialized handling.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress_type: Option<ProgressType>,
    /// Structured task updates for task wait progress.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub task_updates: Option<Vec<TaskUpdate>>,
    /// Overall progress percentage from 0.0 to 100.0.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub progress: Option<f64>,
}

/// Type of progress update.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ProgressType {
    /// Command output streaming.
    CommandOutput,
    /// Task wait progress with structured updates.
    TaskWait,
    /// Generic progress.
    Generic,
}

/// Structured task status update.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TaskUpdate {
    pub task_id: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_preview: Option<String>,
    /// Whether this is a target task being waited on.
    #[serde(default)]
    pub is_target: bool,
    /// Pause information for paused subagent tasks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pause_info: Option<TaskPauseInfo>,
}

/// Pause information for subagent tasks awaiting approval.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TaskPauseInfo {
    /// The agent's message before pausing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub agent_message: Option<String>,
    /// Pending tool calls awaiting approval.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pending_tool_calls: Option<Vec<crate::models::async_manifest::PendingToolCall>>,
}

pub use crate::models::tools::ask_user::{
    AskUserAnswer, AskUserOption, AskUserQuestion, AskUserRequest, AskUserResult,
};
