use ratatui::style::Color;
use stakpak_api::models::ListRuleBook;
use stakpak_shared::models::{
    integrations::openai::{AgentModel, ToolCall, ToolCallResult, ToolCallResultProgress},
    llm::{LLMModel, LLMTokenUsage},
};
use uuid::Uuid;

use crate::app::{LoadingOperation, SessionInfo};

#[derive(Debug)]
pub enum InputEvent {
    AssistantMessage(String),
    AddUserMessage(String),
    StreamAssistantMessage(Uuid, String),
    RunToolCall(ToolCall),
    ToolResult(ToolCallResult),
    StreamToolResult(ToolCallResultProgress),
    StartLoadingOperation(LoadingOperation),
    EndLoadingOperation(LoadingOperation),
    InputChanged(char),
    ShellMode,
    RunShellCommand(String),
    /// Spawn the user's shell and then execute a command in it (for interactive stall recovery)
    RunShellWithCommand(String),
    GetStatus(String),
    BillingInfoLoaded(stakpak_shared::models::billing::BillingResponse),
    Error(String),
    SetSessions(Vec<SessionInfo>),
    InputBackspace,
    InputChangedNewline,
    InputSubmitted,
    InputSubmittedWith(String),
    InputSubmittedWithColor(String, Color),
    MessageToolCalls(Vec<ToolCall>),
    ScrollUp,
    ScrollDown,
    PageUp,
    PageDown,
    DropdownUp,
    DropdownDown,
    Up,
    Down,
    Quit,
    HandleEsc,
    HandleReject(Option<String>, bool, Option<Color>),
    CursorLeft,
    CursorRight,
    ToggleCursorVisible,
    Resized(u16, u16),
    ShowConfirmationDialog(ToolCall),
    HasUserMessage,
    Tab,
    ToggleApprovalStatus,
    ShellOutput(String),
    ShellError(String),
    ShellWaitingForInput,
    ShellCompleted(i32),
    ShellClear,
    ShellKill,
    HandlePaste(String),
    /// Ctrl+V clipboard image paste (non-text, via system clipboard).
    HandleClipboardImagePaste,
    InputDelete,
    InputDeleteWord,
    InputCursorStart,
    InputCursorEnd,
    InputCursorPrevWord,
    InputCursorNextWord,
    ToggleAutoApprove,
    AutoApproveCurrentTool,
    ToggleDialogFocus,
    RetryLastToolCall,
    /// Interactive stall detected - automatically switch to shell mode and fire the command
    InteractiveStallDetected(String),
    AttemptQuit,
    ToggleCollapsedMessages,
    ShowFileChangesPopup,
    FileChangesRevertFile,
    FileChangesRevertAll,
    FileChangesOpenEditor,
    EmergencyClearTerminal,
    ToggleMouseCapture,
    OpenFileInEditor,
    // Approval popup events
    ApprovalPopupNextTab,
    ApprovalPopupPrevTab,
    ApprovalPopupToggleApproval,
    ApprovalPopupSubmit,
    ApprovalPopupEscape,
    // Profile switcher events
    ShowProfileSwitcher,
    ProfilesLoaded(Vec<String>, String),
    ProfileSwitchRequested(String),
    ProfileSwitchProgress(String),
    ProfileSwitchComplete(String),
    ProfileSwitchFailed(String),
    // Command palette events
    ShowCommandPalette,
    CommandPaletteSearchInputChanged(char),
    CommandPaletteSearchBackspace,
    ProfileSwitcherSelect,
    ProfileSwitcherCancel,
    // Shortcuts popup events
    ShowShortcuts,
    ShortcutsCancel,

    // Rulebook switcher events
    ShowRulebookSwitcher,
    RulebooksLoaded(Vec<ListRuleBook>),
    CurrentRulebooksLoaded(Vec<String>),
    RulebookSwitcherSelect,
    RulebookSwitcherToggle,
    RulebookSwitcherCancel,
    RulebookSwitcherConfirm,
    RulebookSwitcherSelectAll,
    RulebookSwitcherDeselectAll,
    RulebookSearchInputChanged(char),
    RulebookSearchBackspace,
    HandleCtrlS,
    ToggleMoreShortcuts,
    // Usage tracking events
    StreamUsage(LLMTokenUsage),
    RequestTotalUsage,
    TotalUsage(LLMTokenUsage),

    // Model events
    StreamModel(LLMModel),

    // Side panel events
    ToggleSidePanel,
    SidePanelNextSection,
    SidePanelToggleSection,
    MouseClick(u16, u16),
}

#[derive(Debug)]
pub enum OutputEvent {
    UserMessage(
        String,
        Option<Vec<ToolCallResult>>,
        Vec<stakpak_shared::models::integrations::openai::ContentPart>,
    ),
    AcceptTool(ToolCall),
    RejectTool(ToolCall, bool),
    ListSessions,
    SwitchToSession(String),
    NewSession,
    Memorize,
    SendToolResult(ToolCallResult, bool, Vec<ToolCall>),
    ResumeSession,
    RequestProfileSwitch(String),
    RequestRulebookUpdate(Vec<String>),
    RequestCurrentRulebooks,
    RequestTotalUsage,
    SwitchModel(AgentModel),
}
