use ratatui::style::Color;
use stakai::Model;
use stakpak_api::models::ListRuleBook;
use stakpak_shared::models::{
    integrations::openai::{ToolCall, ToolCallResult, ToolCallResultProgress, ToolCallStreamInfo},
    llm::LLMTokenUsage,
};
use uuid::Uuid;

use crate::app::{ExistingPlanPrompt, LoadingOperation, SessionInfo};
use crate::services::board_tasks::FetchTasksResult;

#[derive(Debug)]
pub enum InputEvent {
    AssistantMessage(String),
    AddUserMessage(String),
    StreamAssistantMessage(Uuid, String),
    RunToolCall(ToolCall),
    ToolResult(ToolCallResult),
    StreamToolResult(ToolCallResultProgress),
    /// Progress update while tool calls are being streamed/generated by the LLM
    StreamToolCallProgress(Vec<ToolCallStreamInfo>),
    StartLoadingOperation(LoadingOperation),
    EndLoadingOperation(LoadingOperation),
    InputChanged(char),
    ShellMode,
    RunShellCommand(String),
    /// Spawn the user's shell and then execute a command in it (for interactive stall recovery)
    RunShellWithCommand(String),
    GetStatus(String),
    BillingInfoLoaded(stakpak_shared::models::billing::BillingResponse),
    Error(String),
    SetSessions(Vec<SessionInfo>),
    InputBackspace,
    InputChangedNewline,
    InputSubmitted,
    InputSubmittedWith(String),
    InputSubmittedWithColor(String, Color),
    MessageToolCalls(Vec<ToolCall>),
    ScrollUp,
    ScrollDown,
    PageUp,
    PageDown,
    DropdownUp,
    DropdownDown,
    Up,
    Down,
    Quit,
    HandleEsc,
    HandleReject(Option<String>, bool, Option<Color>),
    CursorLeft,
    CursorRight,
    ToggleCursorVisible,
    Resized(u16, u16),
    ShowConfirmationDialog(ToolCall),
    HasUserMessage,
    Tab,
    ToggleApprovalStatus,
    ShellOutput(String),
    ShellError(String),
    ShellWaitingForInput,
    ShellCompleted(i32),
    ShellClear,
    ShellKill,
    HandlePaste(String),
    /// Ctrl+V clipboard image paste (non-text, via system clipboard).
    HandleClipboardImagePaste,
    InputDelete,
    InputDeleteWord,
    InputCursorStart,
    InputCursorEnd,
    InputCursorPrevWord,
    InputCursorNextWord,
    ToggleAutoApprove,
    AutoApproveCurrentTool,
    ToggleDialogFocus,
    RetryLastToolCall,
    /// Interactive stall detected - automatically switch to shell mode and fire the command
    InteractiveStallDetected(String),
    AttemptQuit,
    ToggleCollapsedMessages,
    ShowFileChangesPopup,
    FileChangesRevertFile,
    FileChangesRevertAll,
    FileChangesOpenEditor,
    EmergencyClearTerminal,
    ToggleMouseCapture,
    OpenFileInEditor,
    // Approval popup events
    ApprovalPopupNextTab,
    ApprovalPopupPrevTab,
    ApprovalPopupToggleApproval,
    ApprovalPopupSubmit,
    ApprovalPopupEscape,
    // Approval bar events (inline approval)
    ApprovalBarApproveAll,
    ApprovalBarRejectAll,
    ApprovalBarSelectAction(usize),
    ApprovalBarApproveSelected,
    ApprovalBarRejectSelected,
    ApprovalBarNextAction,
    ApprovalBarPrevAction,
    ApprovalBarCollapse,
    // Profile switcher events
    ShowProfileSwitcher,
    ProfilesLoaded(Vec<String>, String),
    ProfileSwitchRequested(String),
    ProfileSwitchProgress(String),
    ProfileSwitchComplete(String),
    ProfileSwitchFailed(String),
    // Command palette events
    ShowCommandPalette,
    CommandPaletteSearchInputChanged(char),
    CommandPaletteSearchBackspace,
    ProfileSwitcherSelect,
    ProfileSwitcherCancel,
    // Shortcuts popup events
    ShowShortcuts,
    ShortcutsCancel,

    // Rulebook switcher events
    ShowRulebookSwitcher,
    RulebooksLoaded(Vec<ListRuleBook>),
    CurrentRulebooksLoaded(Vec<String>),
    RulebookSwitcherSelect,
    RulebookSwitcherToggle,
    RulebookSwitcherCancel,
    RulebookSwitcherConfirm,
    RulebookSwitcherSelectAll,
    RulebookSwitcherDeselectAll,
    RulebookSearchInputChanged(char),
    RulebookSearchBackspace,
    HandleCtrlS,
    ToggleMoreShortcuts,
    // Usage tracking events
    StreamUsage(LLMTokenUsage),
    RequestTotalUsage,
    TotalUsage(LLMTokenUsage),

    // Model events
    StreamModel(Model),

    // Model switcher events
    ShowModelSwitcher,
    AvailableModelsLoaded(Vec<Model>),
    ModelSwitcherSelect,
    ModelSwitcherCancel,
    ModelSwitcherSearchInputChanged(char),
    ModelSwitcherSearchBackspace,

    // Side panel events
    ToggleSidePanel,
    SidePanelNextSection,
    SidePanelToggleSection,
    MouseClick(u16, u16),

    // Board tasks events
    RefreshBoardTasks,
    BoardTasksLoaded(FetchTasksResult),
    BoardTasksError(String),

    // Plan mode events
    /// Plan mode toggled on/off (sent from backend to TUI to sync state)
    PlanModeChanged(bool),
    /// Existing plan found at startup — show the modal with metadata and stashed prompt
    ExistingPlanFound(ExistingPlanPrompt),
    /// Toggle plan review overlay (Ctrl+P in plan mode)
    TogglePlanReview,
    /// Close plan review overlay
    PlanReviewClose,
    /// Move cursor up in plan review
    PlanReviewCursorUp,
    /// Move cursor down in plan review
    PlanReviewCursorDown,
    /// Open comment modal for current line
    PlanReviewComment,
    /// Approve the plan
    PlanReviewApprove,
    /// Submit feedback (unresolved comments)
    PlanReviewFeedback,
    /// Jump to next commented line
    PlanReviewNextComment,
    /// Jump to previous commented line
    PlanReviewPrevComment,
    /// Toggle resolve on selected comment
    PlanReviewResolve,
    /// Scroll plan review up by a page
    PlanReviewPageUp,
    /// Scroll plan review down by a page
    PlanReviewPageDown,

    // Ask User popup events
    ShowAskUserPopup(
        ToolCall,
        Vec<stakpak_shared::models::integrations::openai::AskUserQuestion>,
    ),
    AskUserNextTab,
    AskUserPrevTab,
    AskUserNextOption,
    AskUserPrevOption,
    AskUserSelectOption,
    AskUserCustomInputChanged(char),
    AskUserCustomInputBackspace,
    AskUserCustomInputDelete,
    AskUserSubmit,
    AskUserCancel,
}

#[derive(Debug)]
pub enum OutputEvent {
    UserMessage(
        String,
        Option<Vec<ToolCallResult>>,
        Vec<stakpak_shared::models::integrations::openai::ContentPart>,
    ),
    AcceptTool(ToolCall),
    RejectTool(ToolCall, bool),
    ListSessions,
    SwitchToSession(String),
    NewSession,
    Memorize,
    SendToolResult(ToolCallResult, bool, Vec<ToolCall>),
    ResumeSession,
    RequestProfileSwitch(String),
    RequestRulebookUpdate(Vec<String>),
    RequestCurrentRulebooks,
    RequestTotalUsage,
    RequestAvailableModels,
    SwitchToModel(Model),
    /// Plan mode activated via /plan command. Contains optional inline prompt.
    PlanModeActivated(Option<String>),
    /// Feedback on the plan — formatted unresolved comments injected as user message.
    PlanFeedback(String),
    /// Plan approved — transition to Executing phase.
    PlanApproved,
    /// Response from ask_user popup with the tool call and result
    AskUserResponse(ToolCallResult),
}
