use ratatui::style::Color;
use stakpak_api::ListRuleBook;
use stakpak_shared::models::integrations::openai::{
    AgentModel, ToolCall, ToolCallResult, ToolCallResultProgress,
};
use uuid::Uuid;

use crate::app::{LoadingOperation, SessionInfo};

#[derive(Debug)]
pub enum InputEvent {
    AssistantMessage(String),
    AddUserMessage(String),
    StreamAssistantMessage(Uuid, String),
    RunToolCall(ToolCall),
    ToolResult(ToolCallResult),
    StreamToolResult(ToolCallResultProgress),
    StartLoadingOperation(LoadingOperation),
    EndLoadingOperation(LoadingOperation),
    InputChanged(char),
    ShellMode,
    GetStatus(String),
    Error(String),
    SetSessions(Vec<SessionInfo>),
    InputBackspace,
    InputChangedNewline,
    InputSubmitted,
    InputSubmittedWith(String),
    InputSubmittedWithColor(String, Color),
    MessageToolCalls(Vec<ToolCall>),
    ScrollUp,
    ScrollDown,
    PageUp,
    PageDown,
    DropdownUp,
    DropdownDown,
    Up,
    Down,
    Quit,
    HandleEsc,
    HandleReject(Option<String>, bool, Option<Color>),
    CursorLeft,
    CursorRight,
    ToggleCursorVisible,
    Resized(u16, u16),
    ShowConfirmationDialog(ToolCall),
    HasUserMessage,
    Tab,
    ToggleApprovalStatus,
    ShellOutput(String),
    ShellError(String),
    ShellWaitingForInput,
    ShellCompleted(i32),
    ShellClear,
    ShellKill,
    HandlePaste(String),
    InputDelete,
    InputDeleteWord,
    InputCursorStart,
    InputCursorEnd,
    InputCursorPrevWord,
    InputCursorNextWord,
    ToggleAutoApprove,
    AutoApproveCurrentTool,
    ToggleDialogFocus,
    RetryLastToolCall,
    AttemptQuit,
    ToggleCollapsedMessages,
    ToggleContextPopup,
    EmergencyClearTerminal,
    ToggleMouseCapture,
    // Approval popup events
    ApprovalPopupNextTab,
    ApprovalPopupPrevTab,
    ApprovalPopupToggleApproval,
    ApprovalPopupSubmit,
    ApprovalPopupEscape,
    // Profile switcher events
    ShowProfileSwitcher,
    ProfilesLoaded(Vec<String>, String),
    ProfileSwitchRequested(String),
    ProfileSwitchProgress(String),
    ProfileSwitchComplete(String),
    ProfileSwitchFailed(String),
    // Command palette events
    ShowCommandPalette,
    CommandPaletteSearchInputChanged(char),
    CommandPaletteSearchBackspace,
    ProfileSwitcherSelect,
    ProfileSwitcherCancel,
    // Shortcuts popup events
    ShowShortcuts,
    ShortcutsCancel,

    // Rulebook switcher events
    ShowRulebookSwitcher,
    RulebooksLoaded(Vec<ListRuleBook>),
    CurrentRulebooksLoaded(Vec<String>),
    RulebookSwitcherSelect,
    RulebookSwitcherToggle,
    RulebookSwitcherCancel,
    RulebookSwitcherConfirm,
    RulebookSwitcherSelectAll,
    RulebookSwitcherDeselectAll,
    RulebookSearchInputChanged(char),
    RulebookSearchBackspace,
    HandleCtrlS,
    ToggleMoreShortcuts,
    // Usage tracking events
    StreamUsage(stakpak_shared::models::integrations::openai::Usage),
    RequestTotalUsage,
    TotalUsage(stakpak_shared::models::integrations::openai::Usage),
}

#[derive(Debug)]
pub enum OutputEvent {
    UserMessage(String, Option<Vec<ToolCallResult>>),
    AcceptTool(ToolCall),
    RejectTool(ToolCall, bool),
    ListSessions,
    SwitchToSession(String),
    NewSession,
    Memorize,
    SendToolResult(ToolCallResult, bool, Vec<ToolCall>),
    ResumeSession,
    RequestProfileSwitch(String),
    RequestRulebookUpdate(Vec<String>),
    RequestCurrentRulebooks,
    RequestTotalUsage,
    SwitchModel(AgentModel),
}
