pub mod auth;
pub mod checkpoint_store;
pub mod error;
pub mod event_log;
pub mod idempotency;
pub mod message_bridge;
pub mod openapi;
pub mod routes;
pub mod sandbox;
pub mod session_actor;
pub mod session_manager;
pub mod state;
pub mod types;

pub use auth::AuthConfig;
pub use checkpoint_store::CheckpointStore;
pub use error::SessionManagerError;
pub use event_log::{EventEnvelope, EventLog, EventSubscription, GapDetected};
pub use idempotency::{IdempotencyRequest, IdempotencyStore, LookupResult, StoredResponse};
pub use openapi::generate_openapi;
pub use routes::{protected_router, public_router, router};
pub use sandbox::{SandboxConfig, SandboxedMcpServer};
pub use session_actor::{build_checkpoint_envelope, build_run_context, spawn_session_actor};
pub use session_manager::SessionManager;
pub use stakpak_agent_core::{ToolApprovalAction, ToolApprovalPolicy};
pub use state::AppState;
pub use types::{SessionHandle, SessionRuntimeState};
